# telegram_master_control.py (FINAL MASTER FILE - SINGLE BOT)

# --- TELEGRAM_INTEGRATION_STATUS - "ACTIVATED HIGH PRIORITY"
# --- MODE - "Zero-Delay Direct Command Integration"

# 1. BOT TOKEN (NEO COBALT)
ALPHA_BOT_TOKEN = "8549799572:AAGtVouG2A74Ls7mmbaDH9xYal6-WOdzaA"

# 2. MASTER CHAT ID
MASTER_CHAT_ID = "6050992457"

# --- EMAIL REPORTING STATUS ---
# STATUS: "OVERRIDDEN_BY_TELEGRAM_PROTOCOL"
