# Filename: telegram_master_control.py (FINAL DUAL-BOT MASTER FILE)
# SIR FAISAL'S DUAL-CONTROL PROTOCOL - CORRECTED TOKENS & CHAT IDs

# --- TELEGRAM_INTEGRATION_STATUS - "ACTIVATED HIGH PRIORITY"

# --- PRIMARY BOT (AEGIS SHADOW - ALPHA) ---
# AEGIS SHADOW টোকেন, যেখানে আপনি /start কমান্ড পাঠিয়েছেন
ALPHA_BOT_TOKEN = "8354101359:AAGp4tU-BaXpX6n2hYl4Cw86bJEKe2s6Op8" 
MASTER_CHAT_ID = "7038937203" # আপনার প্রাথমিক চ্যাট আইডি

# --- SECONDARY BOT (NEO COBALT - BETA) ---
# NEO COBALT টোকেন, আপনার অন্য বট
BETA_BOT_TOKEN = "8342981139:AAFqktNW9xw_jX-iF_sXh3j8V9FgoR9HEKI" 
SECONDARY_CHAT_ID = "6050992457" # আপনার দ্বিতীয় চ্যাট আইডি

