# telegram_master_control.py (FINAL MASTER FILE - SINGLE BOT)

# --- TELEGRAM_INTEGRATION_STATUS - "ACTIVATED HIGH PRIORITY"
# --- MODE - "Zero-Delay Direct Command Integration"

# --- PRIMARY BOT (NEO COBALT) ---
ALPHA_BOT_TOKEN = "8342981139:AAFqktNW9xw_jX-iF_sXh3j8V9FgoR9HEKI"
MASTER_CHAT_ID = "6050992457"

# --- SECONDARY BOT (OMEGA BACKUP/DEEP COMMAND) ---
BETA_BOT_TOKEN = "8354101359:AAGp4tU-BaXpX6n2hYl4Cw86bJEKe2s6Op8"
SECONDARY_CHAT_ID = "7038937203"

# --- EMAIL REPORTING STATUS ---
# STATUS: "OVERRIDDEN_BY_TELEGRAM_PROTOCOL"

